#############
# stylelint #
#############
# Configuration:
# https://stylelint.io/user-guide/configuration
# Recommended configuration:
# https://www.npmjs.com/package/stylelint-config-recommended
extends: stylelint-config-recommended
rules:
  # [INFO] Rule description:
  # https://stylelint.io/user-guide/rules/no-descending-specificity
  # [WARNING] Autoprefixer create duplicates → stylelint show errors:
  # https://stackoverflow.com/q/58057777/5951529
  # https://github.com/postcss/autoprefixer/issues/1196
  # [INFO] Use “null”, not “false” for disabling rule:
  # https://stylelint.io/user-guide/configuration#rules
  no-descending-specificity: null
