#############
# Travis CI #
#############
# Continuous integration for Ubuntu:
# https://travis-ci.org/
# [WARNING] “group: travis_latest” doesn't work at April 2018, read end of article:
# https://blog.travis-ci.com/2017-12-01-new-update-schedule-for-linux-build-images
# Don't download all repository history, that save a time:
# https://docs.travis-ci.com/user/customizing-the-build/#Git-Clone-Depth
git:
  depth: 1

# Trusty by default:
# https://stackoverflow.com/a/21133609/5951529
# https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming
# Travis CI doesn't support 32-bit platforms:
# https://stackoverflow.com/a/37087813/5951529
language: python

python: 3.6

# Multiple scripts
# http://bit.ly/2ow2DvL
env:
# “grunt default” = “grunt”;
# Travis CI support blank value.
- GRUNT_COMMAND=
- GRUNT_COMMAND=publish

# Sections:
# https://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle
# https://stackoverflow.com/a/34384262/5951529
# Exit codes:
# https://docs.travis-ci.com/user/customizing-the-build/#Breaking-the-Build

before_install:
# Virtual environment inside project directory:
# https://jcutrer.com/howto/dev/python/pipenv-pipfile
# “setx PIPENV_VENV_IN_PROJECT 1” for Windows
- export PIPENV_VENV_IN_PROJECT=1
# Ignore already existing virtual environments:
# https://github.com/menzenski/pipenv-travis-test/blob/develop/.travis.yml
- export PIPENV_IGNORE_VIRTUALENVS=1
# That script run for “master” branch, not for “HEAD”;
# Needs, that “grunt-checkbranch” works correct:
# https://stackoverflow.com/a/18866140/5951529
- git checkout master
# Correct displaying Non-ASCII symbols in Travis CI console:
# https://stackoverflow.com/a/34549249/5951529
- git config --global core.quotePath false

install:
# [NOTE] Parallelshell works, but no time economy, compare:
# https://travis-ci.org/Kristinita/SashaPelicanTest/jobs/347254717
# https://travis-ci.org/Kristinita/SashaPelicanTest/jobs/347267767
- sudo apt-get install parallel
- bash ci/travis-install.sh

script:
- grunt $GRUNT_COMMAND
# [WARNING] Don't move these commands to “after_success” section,
# exit code = 0 in this section always:
# https://blog.travis-ci.com/after_script_behavior_changes/
# https://github.com/travis-ci/travis-ci/issues/758
# https://travis-ci.org/Kristinita/KristinitaPelican/jobs/368968780
# [WARNING] I don't use Build Stages, because each stage run in new virtual machine,
# no data persistence → it takes a lot of time, that install and compile all dependencies before stages.
# This is unnecessary in my case.
# https://docs.travis-ci.com/user/build-stages/#Data-persistence-between-stages-and-jobs
- grunt validatesource validateoutput remote travis

# Automatically deploy site to GitHub Pages:
# https://docs.travis-ci.com/user/deployment
# https://docs.travis-ci.com/user/deployment/pages/
# Changes not deploy, if pull request:
# https://docs.travis-ci.com/user/deployment#Pull-Requests
# If “script” failed, deploying doesn't run;
# else “pelican_scaffold”, deploy run, even if “script” failed, don't use “pelican_scaffold”:
# https://github.com/textbook/pelican_scaffold
# [WARNING] Custom commit messages doesn't support:
# https://github.com/travis-ci/travis-ci/issues/9287
deploy:
  provider: pages
  on:
    branch: master
    # Deploy site, only if “grunt publish”, if “grunt” — not deploy:
    # https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on%3A
    condition: $GRUNT_COMMAND = publish
  # [DONE]
  # # [FIXME] Downgrade dpl for correct deploying to GitHub Pages:
  # # https://github.com/travis-ci/travis-ci/issues/9312
  # edge:
  #   branch: v1.8.47
  # Don't overwrite commit history of destination repository:
  # https://docs.travis-ci.com/user/deployment/pages/
  keep-history: true
  # Don't clean output folder:
  # https://docs.travis-ci.com/user/deployment/pages/
  skip-cleanup: true
  target-branch: master
  local-dir: output
  repo: Kristinita/Kristinita.github.io
  # “GITHUB_TOKEN” is secure variable, that set in repository settings:
  # https://docs.travis-ci.com/user/environment-variables#Defining-Variables-in-Repository-Settings
  # https://docs.travis-ci.com/user/deployment/pages/#Setting-the-GitHub-token
  # [WARNING] You need set secure variables for each repository,
  # variables for all repositories not possible at the time:
  # https://github.com/travis-ci/travis-ci/issues/2069
  github-token: $GITHUB_TOKEN
  # Name and e-mail of committer:
  # https://docs.travis-ci.com/user/deployment/pages/#Further-configuration
  committer-from-gh: true
  # Automatically generate CNAME for custom domain:
  fqdn: Kristinita.ru
  # [WARNING] Don't use single quotes in “project-name”:
  # https://github.com/travis-ci/travis-ci/issues/9325
  project-name: Поиск Кристиниты
  verbose: true
