#############
# Travis CI #
#############
# Continuous integration for Ubuntu:
# https://travis-ci.org/
# [WARNING] If Travis CI doesn't create build for your latest commit,
# your “.travis.yml” file is not valid. Example:
# https://github.com/Kristinita/SashaTravisDebugging/commits/KiraLocalAppVeyor/.travis.yml
# [WARNING] “group: travis_latest” doesn't work at April 2018, read end of article:
# https://blog.travis-ci.com/2017-12-01-new-update-schedule-for-linux-build-images

# Trusty by default:
# https://stackoverflow.com/a/21133609/5951529
# https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming
# Travis CI doesn't support 32-bit platforms:
# https://stackoverflow.com/a/37087813/5951529
# I use Trusty with sudo required:
# https://docs.travis-ci.com/user/reference/overview/#Virtualisation-Environment-vs-Operating-System
# Possibly, Trusty — more modern, so by default:
# https://docs.travis-ci.com/user/reference/trusty/#Image-differences-from-Precise
# https://blog.travis-ci.com/2017-08-31-trusty-as-default-status

# Needs for correct APT addon usage:
# https://docs.travis-ci.com/user/reference/overview/
# Diff:
# https://travis-ci.org/Kristinita/SashaScrutinizer/builds/370138075
# https://travis-ci.org/Kristinita/SashaScrutinizer/builds/370122401
sudo: enabled

# Needs Xenial, not Trusty for Python 3.7 works:
# https://travis-ci.community/t/unable-to-download-python-3-7-archive-on-travis-ci/639/2
# https://github.com/travis-ci/travis-ci/issues/9815#issuecomment-425867404
# Differences between Xenial and Trusty:
# https://docs.travis-ci.com/user/reference/xenial/#differences-from-the-trusty-images
dist: xenial

# [INFO] Don't download all repository history, that save a time:
# https://docs.travis-ci.com/user/customizing-the-build/#Git-Clone-Depth
git:
  depth: 1

# Environment:
# [INFO] Using secure variables for Travis CI:
# https://docs.travis-ci.com/user/environment-variables/#defining-encrypted-variables-in-travisyml
# [INFO] Encrypt variables locally:
# https://docs.travis-ci.com/user/environment-variables/#encrypting-environment-variables
env:
  global:
  # [INFO] Needs get GitHub token with “public_repo” scope:
  # https://docs.travis-ci.com/user/deployment/pages/#setting-the-github-token
  # [INFO] YAML multiline strings:
  # https://stackoverflow.com/a/21699210/5951529
  # https://yaml-multiline.info/
  # [INFO] Equivalent: TOKEN_GITHUB_FOR_TRAVIS_DEPLOY = my real token
  - secure: >
      "EXm44fDtI7y2hCnp6uK3gIFMWUMUink3dO9qCXXfd5LwoK53fcXhoDtF+/
      xve7jKFLsUSm5EAJxPiGiNILyOymJkOthTmz+Bohnd1B27jaZepCbh10wxalj7Aw405hBux+z0l2pq21YlbFZl+QyvU/
      8KMms7VVeBDYSCQTFQEmHb5BmA+U2lxJ1hQLJmYK8oV96hKSD/
      kxgL80EfshoNELXvquC16GwNceJNNeb5cYPMUgb6hdDWEez3mtD9htJO8aFx4XV1/5a7Wu55UOHO/i79o8aT/
      O94/bDrtOgHBT3btTmQteeZ1ThAWoHf42mfLxNLxLkAO4YgEOXifkCRp56klfRQ6lwg0fe1/nufiPXuxQDKq/OKqWXgYDQ3Jip5u/
      hcqyQQXnruSszFJT8vW6Ggd0Rr9yRNzATfxgjDEQ15tx/gIWLrLrofbUfcmOn/
      fO4zDWyH4fcs+HJ10qY42UH0OanZe2eOCheC6eYkUOS1RlmY0CDH43c6xJ1SWVnhj6ybuopoJImcaEkk/
      OfjHmtWltGi71IPcyccfji6Uy41wg37D4DUq4cs3T0WX0tD3WfmKc98WtI9/
      iIUEWZhNleS6lCjGIapFdso23hwzKILzCx+tO9KGAenhTGbarq+Fyqfa/
      TmzyHNAk1KwZGgaOrGgCLNPZx3aT7bibx+6JI="
  # [INFO] Equivalent: API_KEY_APPVEYOR = my real key:
  # https://kristinita.ru/Pages/About-for-developers#AppVeyor
  - secure: >
      "qE2c+aZb9QGtPF9VG6WhAP2iT0mTDAnmueEiqWUctgalhAFAJ4wdSqvHNNv+F2178wE92WcpT3/
      chmJltlBj1Qqx6vWevJR2ff1uNbQnwGHYBw+1c8JOvx7mUvisp/nzU1eIpU50/
      uDMF6PnUQ7j269nE1seEjUo7aP98rVHDXZ1uYaOVIEKq40HhLMOlfQg4mhpN1zxQLL7eCy7YgQWXDUb4yRT6TU1BxI3uIC9y8LVgv0le3L8hikD2yR
      ++wJwFHSu9nTm9/
      liSxCb4TINZ/mILZ7nzC4UWfNqwRgzz+5n4klcHxeuDORRh9dFQnN3EGsdrScf0Re1oDdUezdYkvgCRzWIgYYPn0FNnmuZl3ccg6JDhRyV+
      LzTv+XiosDojqdHr7R10ae/
      2gyExR+uARIvf0dFnTIBztVnKRtzuPYdsPOkU7R6rM8FnMAjK4G5yjJO4QcZqMo+BzY8O2gqWFba6nxhDk1OBWj/14+jU2pfkW8cR4vq3Us/
      upPuNJhHdtv+S5vuuF9/
      CksWBqUi3QMQYkSMT5Xkv5YcTeWqQe6W4U2hVg7+Tl1jesn2WP6nM6j
      +I2W5fJwYWIKB7U0hP6WR0jkrHDvMNfWgaB8VZCxYoVUFvCMf5IBnXgRGkYjJn9KkQv3pfODC5aUdep2mCWL+cYiHBukRncS66bs/
      EAE="

# Needs “language: bash” for multilanguage projects:
# https://github.com/travis-ci/travis-ci/issues/4895
# https://github.com/travis-ci/docs-travis-ci-com/issues/910
# But that use latest Python 3 version, not Python 2, you need “language: python” or
# install Python via APT addon:
# https://stackoverflow.com/a/37660551/5951529
# https://travis-ci.org/Kristinita/SashaScrutinizer/builds/370118828
# https://github.com/travis-ci/travis-ci/issues/9180
language: python

python: 3.7

# [DEPRECATED] Doesn't work on Travis CI, needs “matrix.include”:
# https://github.com/travis-ci/travis-ci/issues/9634
# # Multiple scripts
# # https://docs.travis-ci.com/user/speeding-up-the-build/#Parallelizing-your-builds-across-virtual-machines
# env:
# # “grunt default” = “grunt”;
# # Travis CI support blank value.
# - GRUNT_COMMAND=
# # If http-server run in background, “pipenv run pelican content -s publishconf.py”
# # command can't move “theme” folder.
# # I can't find method for http-server stop
# - GRUNT_COMMAND=default && grunt http-server screenshots && grunt publish

# [INFO] “matrix.include”:
# https://docs.travis-ci.com/user/customizing-the-build#Explicitly-Including-Jobs
matrix:
  include:
  - script:
    - grunt
    - grunt http-server validatedev && grunt validate remote travis
  - script:
    # [BUG] pageres doesn't work with Node.js 11:
    # https://github.com/sindresorhus/pageres/issues/344
    # - grunt default && grunt http-server screenshots && grunt publish
    - grunt publish
    - grunt validate remote travis
    # Deploy, if production, not dev build:
    # https://travis-ci.org/Kristinita/SashaTravis/builds/381271402
    # Make as cotila:
    # https://github.com/calebzulawski/cotila/blob/master/.travis.yml
    - MATRIX_DEPLOY=1

# Sections:
# https://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle
# https://stackoverflow.com/a/34384262/5951529
# Exit codes:
# https://docs.travis-ci.com/user/customizing-the-build/#Breaking-the-Build

# Addons:
# https://docs.travis-ci.com/user/addons/
# APT addon:
# https://docs.travis-ci.com/user/installing-dependencies/#Installing-Packages-with-the-APT-Addon
# APT sources whitelist:
# https://github.com/travis-ci/apt-source-whitelist
# APT package whitelist:
# https://github.com/travis-ci/apt-package-whitelist
# [NOTE] ShellCheck default in Travis CI configuration:
# https://github.com/koalaman/shellcheck#travis-ci
# PhantomJS is preinstalled on Travis:
# https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-phantomjs
addons:
  apt:
    packages:
    - parallel
    # [INFO] For HTML Tidy building:
    # https://askubuntu.com/a/1027128/582218
    - xsltproc

# Cache not needed for this project.
# Cache needs, when 1 job install dependencies, another jobs runs test, using the cache:
# https://docs.travis-ci.com/user/build-stages/warm-cache/
# Cache upload after “script” phase:
# https://docs.travis-ci.com/user/caching/#Build-phases
# Cache doesn't save between “images” — new builds: new virtual machine for each build:
# https://docs.travis-ci.com/user/caching/#Things-not-to-cache

before_install:
# Virtual environment inside project directory:
# https://jcutrer.com/howto/dev/python/pipenv-pipfile
# “setx PIPENV_VENV_IN_PROJECT 1” for Windows
- export PIPENV_VENV_IN_PROJECT=1
# Ignore existing virtual environments:
# https://github.com/menzenski/pipenv-travis-test/blob/develop/.travis.yml
- export PIPENV_IGNORE_VIRTUALENVS=1
# [INFO] Remove .NET Core SDK telemetry:
# https://docs.microsoft.com/en-us/dotnet/core/tools/telemetry#disclosure
# https://stackoverflow.com/a/39307563/5951529
- export DOTNET_CLI_TELEMETRY_OPTOUT=1
# Add LocalAppVeyor directory to the end of the PATH environment variable:
# https://unix.stackexchange.com/a/26067/237999
# http://www.troubleshooters.com/linux/prepostpath.htm
# “.dotnet/tools” must be added to PATH:
# https://github.com/dotnet/cli/issues/9208#issuecomment-386851831
# DotNet user profile is “USERPROFILE” on Windows and “HOME” on Linux:
# https://github.com/dotnet/cli/issues/7569#issuecomment-329280924
# “$HOME” is “/home/travis” on Travis Linux:
# https://docs.travis-ci.com/user/environment-variables/#default-environment-variables
- PATH=$PATH:$HOME/.dotnet/tools
# That script run for “master” branch, not for “HEAD”;
# Needs, that “grunt-checkbranch” works correct:
# https://stackoverflow.com/a/18866140/5951529
- git checkout master
# Correct displaying Non-ASCII symbols in Travis CI console:
# https://stackoverflow.com/a/34549249/5951529
- git config --global core.quotePath false

install:
# [NOTE] Parallelshell works, but no time economy, diff:
# https://travis-ci.org/Kristinita/SashaPelicanTest/jobs/347254717
# https://travis-ci.org/Kristinita/SashaPelicanTest/jobs/347267767
- bash bash/travis-install.sh

# [DEPRECATED] Doesn't work on Travis CI, needs “matrix.include”:
# https://github.com/travis-ci/travis-ci/issues/9634
# script:
# - grunt $GRUNT_COMMAND
# # [WARNING] Don't move these commands to “after_success” section,
# # exit code = 0 in this section always:
# # https://blog.travis-ci.com/after_script_behavior_changes/
# # https://github.com/travis-ci/travis-ci/issues/758
# # https://travis-ci.org/Kristinita/KristinitaPelican/jobs/368968780
# # [WARNING] I don't use Build Stages, because each stage run in new virtual machine,
# # no data persistence → it takes a lot of time, that install and compile all dependencies before stages.
# # This is unnecessary in my case.
# # https://docs.travis-ci.com/user/build-stages/#Data-persistence-between-stages-and-jobs
# - grunt validate remote travis

# [INFO] Automatically deploy site to GitHub Pages:
# https://docs.travis-ci.com/user/deployment
# https://docs.travis-ci.com/user/deployment/pages/
# [INFO] Changes not deploy, if pull request:
# https://docs.travis-ci.com/user/deployment#Pull-Requests
# If “script” failed, deploying doesn't run;
# else “pelican_scaffold”, deploy run, even if “script” failed, don't use “pelican_scaffold”:
# https://github.com/textbook/pelican_scaffold
# [WARNING] Custom commit messages doesn't support:
# https://github.com/travis-ci/travis-ci/issues/9287
deploy:
  provider: pages
  on:
    branch: master
    # Deploy site, if “grunt publish”, else “grunt” — not deploy:
    # https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on%3A
    condition: $MATRIX_DEPLOY
  # [DONE]
  # # [FIXME] Downgrade dpl for correct deploying to GitHub Pages:
  # # https://github.com/travis-ci/travis-ci/issues/9312
  # edge:
  #   branch: v1.8.47
  # Don't overwrite commit history of destination repository:
  # https://docs.travis-ci.com/user/deployment/pages/
  keep-history: true
  # Don't clean output folder:
  # https://docs.travis-ci.com/user/deployment/pages/
  skip-cleanup: true
  target-branch: master
  local-dir: output
  repo: Kristinita/Kristinita.github.io
  # “TOKEN_GITHUB_FOR_TRAVIS_DEPLOY” is secure variable, that set in repository settings:
  # https://docs.travis-ci.com/user/environment-variables#Defining-Variables-in-Repository-Settings
  # https://docs.travis-ci.com/user/deployment/pages/#Setting-the-GitHub-token
  # [WARNING] You need set secure variables for each repository,
  # variables for all repositories not possible at the time:
  # https://github.com/travis-ci/travis-ci/issues/2069
  github-token: $TOKEN_GITHUB_FOR_TRAVIS_DEPLOY
  # Name and e-mail of committer:
  # https://docs.travis-ci.com/user/deployment/pages/#Further-configuration
  committer-from-gh: true
  # [INFO] For custom domains only
  # Automatically generate CNAME for custom domain:
  # fqdn: Kristinita.ru
  # [WARNING] Don't use single quotes in “project-name”:
  # https://github.com/travis-ci/travis-ci/issues/9325
  project-name: Поиск Кристиниты
  verbose: true
