############
# AppVeyor #
############
# Continuous integration for Windows:
# https://www.appveyor.com/docs/
# Configuration:
# https://www.appveyor.com/docs/appveyor-yml/

# [NOTE] I'm doesn't support 32-bit Windows:
# https://www.appveyor.com/docs/appveyor-yml/
platform: x64

# Don't download all repository history, that save a time:
# https://www.appveyor.com/docs/how-to/repository-shallow-clone/#setting-depth-of-git-clone-command
clone_depth: 1

init:
- setx PIPENV_VENV_IN_PROJECT 1
# Needs, because will get messages as:
# «flake8 is not recognized»
# https://github.com/ogrisel/python-appveyor-demo/blob/master/appveyor.yml
# Python 2 by default, see:
# https://www.appveyor.com/docs/build-environment/#python
# https://ci.appveyor.com/project/Kristinita/erichek/build/1.0.3
- SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
# Needs AppVeyor console set, see:
# https://stackoverflow.com/a/48093971/5951529
- set PYTHONIOENCODING=utf-8
# Set latest Ruby version at the time:
# https://www.appveyor.com/docs/lang/ruby/
# https://www.appveyor.com/docs/build-environment/#ruby
- set PATH=C:\Ruby25-x64\bin;%PATH%
# Use “CALL Refreshenv.cmd” for local installation:
# https://github.com/chocolatey/choco/issues/1461#issuecomment-348136706
# https://ss64.com/nt/call.html
- refreshenv

# Configuration
# https://www.appveyor.com/blog/2018/04/25/specialized-build-matrix-configuration-in-appveyor/
# “Debug” configuration is default
configuration:
- Debug
- Release

environment:
  # Variables:
  # https://help.appveyor.com/discussions/problems/4629-how-to-use-appveyor-environment-variable
  # https://help.appveyor.com/discussions/questions/15163-multiuple-build-matrix-dimensions-from-environment-variables
  PYTHON: C:\Python37-x64
  PYTHON_VERSION: 3.7
  PYTHON_ARCH: 64
  # “grunt default” = “grunt”;
  # AppVeyor support blank value.
  # Spaces before “&&” doesn't need, compare:
  # https://ci.appveyor.com/project/Kristinita/sashatravis/build/job/5oqxucp76bpsr51o
  # https://ci.appveyor.com/project/Kristinita/sashatravis/build/1.0.38/job/s52ko615e3fpxr9b
  # [BUG] pageres doesn't work with Node.js 11:
  # https://github.com/sindresorhus/pageres/issues/344
  # GRUNT_COMMAND: default&& grunt http-server screenshots&& grunt publish
  GRUNT_BUILD:
  GRUNT_TEST: validatedev validate remote
  # API key required for LocalAppVeyor:
  # https://www.appveyor.com/docs/api/
  # https://ci.appveyor.com/api-keys
  API_KEY_APPVEYOR:
    # Secure variables:
    # https://www.appveyor.com/docs/build-configuration/#secure-variables
    secure: +tAYCLWvKpNefBmIFHBZzSdFnN8mu71hBU1MqYbrjlY=

# Build configuration:
# https://www.appveyor.com/docs/build-configuration/#build-pipeline
install:
# That script run for “master” branch, not for “HEAD”;
# Needs, that “grunt-checkbranch” works correct:
# https://stackoverflow.com/a/18866140/5951529
# Needs in “install” section, because in “init” section actions before cloning.
- git checkout master
# [NOTE] Console (cmd.exe) is default terminal.
# If needs PowerShell, “ps:” required:
# https://www.appveyor.com/docs/appveyor-yml/
# [WARNING] For local Scoop installation must required:
# “Set-ExecutionPolicy RemoteSigned -scope CurrentUser”
# http://scoop.sh/
- ps: iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
# [WARNING] npm parallel doesn't work, example:
# https://ci.appveyor.com/project/Kristinita/sashapelicantest/build/1.0.25/job/70x5h1qq2d6j8gyp
# [WARNING] start command doesn't work without batch file:
# https://ci.appveyor.com/project/Kristinita/sashapelicantest/build/1.0.31
# Project folder:
# https://github.com/vim/vim-win32-installer/blob/master/appveyor.yml
- '%APPVEYOR_BUILD_FOLDER%/batch/appveyor-install.bat'

build_script:
- grunt %GRUNT_BUILD%

test_script:
- grunt %GRUNT_TEST%

# Simple working configuration:
# https://github.com/Kristinita/SashaAppVeyorDebugging/blob/7ac8c23540c737f403ae280ce6502734833bb85f/appveyor.yml
for:
-
  matrix:
    only:
    - configuration: Release
  environment:
    GRUNT_BUILD: publish
    GRUNT_TEST: validate remote
