##############
# production #
##############
# Settings, specific for production, not development version

# [INFO] Delete extra artifacts from development process
DELETE_OUTPUT_DIRECTORY: true

# [INFO] I want absolute paths for publishing; that users can copy sources of my site.
# But in building process relative paths required for some tools as
# critical, checkPages and clean-console.
# So I’m convert relative paths to absolute after all tasks
# use regular expressions from “grunt string-replace:html-relative-to-absolute-paths”
RELATIVE_URLS: true

# [INFO] About caching:
# https://docs.getpelican.com/en/latest/settings.html#reading-only-modified-content
# [INFO] Changes may be not visible, if cache enabled:
# https://docs.getpelican.com/en/latest/faq.html#changes-to-the-settings-file-take-no-effect
CACHE_CONTENT: false
LOAD_CONTENT_CACHE: false

# [INFO] Add “.min” to stylesheets and scripts extensions in HTML files;
# for example, replace:
# <link rel="stylesheet" href="https://kristinita.netlify.com/theme/css/general/basic.css">
# to
# <link rel="stylesheet" href="https://kristinita.netlify.com/theme/css/general/basic.min.css">
MIN: .min
